### ISSUE TITLE
Chapitre 4.2 : Mise en place des structures

### ISSUE THREAD

**Issue by zatmania** [Anakeen/dynacase-quick-start#15]
Bonjour,

entre les fichiers sources des familles et les captures d'écran (Figure 46. Choisissez vos familles et Figure 47. Choisissez vos familles), il manque la famille Site. Cela n'empêche en rien le bon suivi du quickstart, il s'agit juste d'une petite remarque.

Claude

**Comment by cbonnissent** [comment]
Merci de la remarque, je vais faire quelques modifications pour le prendre en compte.
